---
name: Build Containers on PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-proxyd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build proxyd image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./proxyd/Dockerfile
          platforms: linux/amd64
          push: false
